name: Setup Go
description: Setup Go

inputs:
  go-version:
    description: Go version range to set up.
    default: '>=1.25.0'
  create:
    description: Create the cache
    default: 'false'
  lint-cache:
    description: Restore the golangci-lint cache
    default: 'false'

runs:
  using: composite

  steps:
    - name: Install Go
      id: install-go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: false

    # Avoid hardcoding the cache keys more than once.
    - name: Get cache info
      shell: bash
      id: cache-info
      env:
        MODULES_KEY: go-modules-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ hashFiles('**/go.sum', '**/.custom-gcl.yml') }}
        LINT_KEY: golangci-lint-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}-${{ hashFiles('**/go.sum', '**/.custom-gcl.yml') }}
        BUILD_KEY: go-build-cache-${{ runner.os }}-${{ steps.install-go.outputs.go-version }}
      run: |
        echo "modules-key=$MODULES_KEY" >> $GITHUB_OUTPUT
        echo "lint-key=$LINT_KEY" >> $GITHUB_OUTPUT
        echo "build-key=$BUILD_KEY" >> $GITHUB_OUTPUT
        echo "GOLANGCI_LINT_CACHE=$RUNNER_TEMP/golangci-lint-cache" >> $GITHUB_ENV

    - if: ${{ inputs.create != 'true' }}
      name: Restore Go modules
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-info.outputs.modules-key }}
        path: |
          ~/go/pkg/mod

    - if: ${{ inputs.create != 'true' }}
      name: Restore Go build cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: unused-key-${{ github.run_id }}
        restore-keys: ${{ steps.cache-info.outputs.build-key }}-
        path: |
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - if: ${{ inputs.create != 'true' && inputs.lint-cache == 'true' }}
      name: Restore golangci-lint cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: unused-key-${{ github.run_id }}
        restore-keys: ${{ steps.cache-info.outputs.lint-key }}-
        path: ${{ env.GOLANGCI_LINT_CACHE }}

    - name: Set mtimes
      shell: bash
      run: |
        find . -type f ! -path ./.git/\*\* | go run github.com/slsyy/mtimehash/cmd/mtimehash@v1.0.0 || true
        find . -type d ! -path ./.git/\*\* -exec touch -d '1970-01-01T00:00:01Z' {} + || true

    # All steps below are only run if the cache is being created.

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npm ci

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: |
        go mod download
        cd _tools
        go mod download

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby build

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      id: setup-go-test
      run: npx hereby test

    - if: ${{ failure() && inputs.create == 'true' && steps.setup-go-test.conclusion == 'failure' }}
      shell: bash
      run: git diff --diff-filter=AM --no-index ./testdata/baselines/reference ./testdata/baselines/local

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby test --coverage

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby lint

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx hereby lint --noembed

    - if: ${{ inputs.create == 'true' }}
      shell: bash
      run: npx dprint check

    - if: ${{ inputs.create == 'true' }}
      name: Save Go modules
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-info.outputs.modules-key }}
        path: |
          ~/go/pkg/mod

    - if: ${{ inputs.create == 'true' }}
      name: Save Go build cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-info.outputs.build-key }}-${{ github.run_id }}
        path: |
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~/AppData/Local/go-build

    - if: ${{ inputs.create == 'true' }}
      name: Save golangci-lint cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-info.outputs.lint-key }}-${{ github.run_id }}
        path: ${{ env.GOLANGCI_LINT_CACHE }}
